name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
    - name: DockerHub authentication
      run: docker login --password $DOCKER_PASSWORD --username $DOCKER_USER
    - name: Build Docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: | 
        docker build . --file Dockerfile \
          --tag $DOCKER_USER/docker-graphql:$NEW_VERSION \
          --tag $DOCKER_USER/docker-graphql:latest
    - name: Push Docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push $DOCKER_USER/docker-graphql:$NEW_VERSION
        docker push $DOCKER_USER/docker-graphql:latest
