name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: DockerHub authentication
      run: docker login --password $DOCKER_PASSWORD --username $DOCKER_USER
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/docker-graphql:0.0.2
    - name: Push Docker image
      run: docker push $DOCKER_USER/docker-graphql:0.0.2
